### ISSUE TITLE
Player: Pause broken

### ISSUE THREAD

**Issue by vermilion** [vermilion/MiSharp#35]
7a5ee89 Better UI response on track change
Nullreference on pausing

System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Ссылка на объект не указывает на экземпляр объекта.
  Source=MiSharp
  StackTrace:
       в MiSharp.PlaybackController.PlayPause() в f:_repos\MiSharp\MiSharp\ViewModel\Player\PlaybackController.cs:строка 139
       в MiSharp.PlayerViewModel.<.ctor>b__2(Object param) в f:_repos\MiSharp\MiSharp\ViewModel\Player\PlayerViewModel.cs:строка 35
       в System.Reactive.AnonymousObserver`1.OnNextCore(T value)
       в System.Reactive.ObserverBase`1.OnNext(T value)
       в ReactiveUI.ReactiveCommand.marshalFailures[T](Action`1 block, T param)
  InnerException:

**Comment by Aokisensei** [comment]
f854162f7d79f99f8f2e92de4ad280f86dc9a6e3 done with it
